#+TITLE: ADASS Poster
#+Startup: indent
#+TODO: TODO(t) | IN_PROGRESS(p) | DONE(d)
#+TAGS: Bug(b) Improvement(i) Research(r) Experiment(e) Analysys(a)


* Summary

Implementation

http://maps.lsst.rocks/hsc/cosmos

** Questions

What is the take away we want?


* Skyviewer

** 1. Introduction

Sky Viewer Investigations for LSST EPO

LSST Education & Public Outreach (EPO) reports on the early investigations of using and implementing a skyviewer across it's software systems.
We research available open-source skyviewer software and identify requirements and possible features for our implementation.
Over the summer we prototyped an implementation of this using Aladin and Aladin-lite. <this needs information about TNSD design?>


LSST Education & Public Outreach (EPO) reports on the early investigations of using and implementing a skyviewer across it's software systems. We research available open-source skyviewer software and identify requirements and possible features for our implementation. Over the summer we prototyped an implementation of this using Aladin and Aladin-lite. <this needs information about TNSD design?>

The LSST software systems make extensive use of Python, 
with almost all of it initially being developed solely in Python 2. 
Since LSST will be commissioned when Python 2 is end-of-lifed it is critical 
that we have all our code support Python 3 before commissioning begins. Over the 
past year we have made significant progress in migrating the bulk of the 
code from the Data Management system onto Python 3. This poster presents our 
migration methodology, and the current status of the port, with our eventual 
aim to be running completely on Python 3 by early 2018.

** 1. Comparsion 

Modified table from review.

|               | Aladin  | Flat | WorldWideTelescope |
| Projection    | HEALPix | Flat |                    |
| Tile Schema   | HiPS    |      |                    |
| Tile Creation |         |      |                    |
| Examples      |         |      |                    |
| Mobile        | Yes     | Yes  | No                 |


** 2. Projection

We plan to use HealPix<cite_1>.
# This projection has a number of benefits.
It has multiple libraries in Python 3, which has seen extensive use at LSST  and is used in our science notebook investigations<cite_2, cite_3>.
HiPS and MOC, which use HealPix, are IVOA standards<cite_4, cite_5>.
HealPix is acceptable for use with the LSST science pipeline<cite_6> and our formal education science notebook investigations.
HealPix is uniform within the expected coverage of the LSST survey<cite_7 or figure>.

We plan to use HealPix<cite_1>. It has multiple libraries in Python 3, which has seen extensive use at LSST  and is used in our science notebook investigations<cite_2, cite_3>. HiPS and MOC, which use HealPix, are IVOA standards<cite_4, cite_5>. HealPix is acceptable for use with the LSST science pipeline<cite_6> and our formal education science notebook investigations. HealPix is uniform within the expected coverage of the LSST survey<cite_7 or figure>.

** 3. Implementation

We prototyped a skyviewer using Aladin and Aladin Lite <cite_i1, cite_i2>. We used HSC Public Data Release 1 COSMOS data <cite_i3>. This was reprocessed by the LSST DM team using the LSST DM pipeline.

** 3.5 Hybrid


Combine Aladin with other technologies.

DES and Deepzoom.

** Aladin


** 4. User Interface and Design

*** TNSD

LSST EPO performed user

*** Audience

Through configuration

*** Mobile

** 5. Plan

*** Science Notebooks

*** In View

TNSD figure.

*** Object Slider/Page

TNSD figure.

The object slider provides two views. An information view which provides
a higher resolution image of the object and further high level information.
The detail view provides additional scienfic details and infographics.

*** Search & Filters

Paragraph discussion.

*** Collections

*** Citizen Science

HiPS can look terrible and can look weird. Opportunity

* What to choose

1. All sky, not in high resolution.
2. Deep Drilling
3. Selection of Formal Education areas with related catalog data.


* Layout

** Title and details at top center and right - room for logo

** Bibliography at bottom right

** TNSD in center

** Intro top right

** Top left comparison

** Remaining

Center left

Bottom left

Top center

Bottom center

Center right

* Review

** Reviewer #1 Comments

**Citation improvements**
- [X] There are two commas after the second author.
- [X] The Aladin reference looks weird in the introduction with the parens in the wrong place. I think you want `\citep`.
- [X] Aihara reference should use `\citepb`. Also, please use "and others" in the bib file so that all authors are not listed.
- [X] Cite HiPS paper on first usage. The term appears from nowhere in section 3. It's later a footnote to the document but please cite a real paper. Also for MOCS.
- [X] If you are going to mention Python 3 used extensively at LSST, feel free to cite my paper (PUB-46).
- [X] In the table, I don't think ESA and CDS need footnotes as such but maybe those could be URL footnotes to the ESASky page? Real scientific references preferred though.
- [X] `\citep` for HEALPix ref.
- [X] Cite LEP-31 and/or LSE-89 similar to LDM-542.
- [X] Cite Juric et al 2015 DM paper when talking about DM team. Expand "DM" on first usage. Consider citing Bosch et al 2017 HSC pipeline paper after "LSST DM pipeline" with
```
\citep[see e.g.][]{...}
```

**Other**
- [X] Was 16GB the peak usage and was this on a single node? Or 8 nodes all using 16GB peak?
- [X] The introduction is more of a conclusion rather than background. Can you please give introduce why you want a sky viewer and how you expect EPO users to interact with LSST data?
- [X] Can you expand on what contexts "multiple" means in section 2?
- [X] "Norder" seems strange typography. Should that be a subscript?
- [X] I'd like some narrative comparison giving pros and minuses of the approaches in section 4.
- [X] What items identified by TNSD are lacking in current tools? I think it's important to know that.
- [X] Section 6 probably doesn't need to exist as it's really a continuation of the TNSD discussion. I would put those numbered elements in the figure caption and just link to fig 1 at end of section 5.
- [X] Please cite LDM-542 as a document and not a footnote. Put the URL in the URL part of the bib entry.
- [X] The final sentence of conclusions came from nowhere. It isn't a conclusion that is summarizing any previous content. Please move that to the comparison section. Say there that this is a feature that we really need. You can reiterate it in the conclusions.

Added by me.
- [X] Add narrative between sections that makes it more cohesive.

** Reviewer #2 Comments

- [X] Make sure you use "sky viewer" (2 words) where ever you are not referring explicitly to the LSST product (I spot one instance in the Intro). That way you are making a clear distinction between all the options and the eventual "LSST Skyviewer" (which might also have a different name in the future). Or... Ben's suggestion was to use "Sky Atlas" as a generic term (which I don't like) and I suggested using "Sky Map" or "sky map technologies." Maybe Tim Jenness has an opinion on this?
- [X] Regarding Tim's comment on the intro, there are a series of requirements listed in LSE-89 regarding an EPO Portal full-sky viewer. The sentence about TNSD can be expanded as well, something along the lines of... We contracted Theresa Neil: Strategy + Design (TNSD) to build a Proof of Concept sky viewer to test with a variety of intended users of the EPO Portal in order to understand and achieve the needs of our sky viewer audiences
- [X] Section 2, number 3: does this mean usable on a mobile platform?
- [X] Section 3, first sentence refers to "prototype survey" - I think you mean that we wanted to have a sample dataset of color images to populate a prototype sky viewer and the HSC data released was used after reprocessing, etc... Is that right?
- [X] You use "It" a lot in this section and it's not clear where you are referring to the data or the sky viewer or something else... avoid using pronouns, especially "it", whenever possible.
- [X] Using text to give reasons for the decisions you make regarding the sky viewer options in Section 4 is more important (I think for this paper) than what you currently state in Section 5 about the UI (which also does not have any justification for why the features you list in Section 6 were implemented)
- [X] Section 6 can be scrapped and the list included in the caption of the figure
- [X] Conclusion: use of "this" in the first sentence is ambiguous.


